Add babel module resolver
NMF-earth/nmf-app pull request #173
Opened 2020-10-05 00:55 UTC by laurameck

Added babel module resolver. Modified `AboutScreen.tsx` to verify modules were working as expected.

2020-10-05 00:58 UTC, laurameck commented
@PierreBresson let me know if there's another syntax you'd like to use for the modules instead

2020-10-05 11:28 UTC, PierreBresson requested changes
Just a little change needed and we are good to go

2020-10-05 11:28 UTC, PierreBresson commented on package.json
> +    "babel-plugin-module-resolver": "^4.0.0",
Could you remove the "^"? So we all have the same version

2020-10-06 06:50 UTC, PierreBresson approved these changes

2020-10-06 06:51 UTC, merged