Fix imports
NMF-earth/nmf-app pull request #241
Opened 2020-11-01 12:25 UTC by hb2708

✅ I have read the [contributing file](https://github.com/NMF-earth/nmf-app/blob/master/contributing.md)

## Summary

## Changelog

## Demo

2020-11-01 15:36 UTC, hb2708 commented
@PierreBresson Ready for review

Imports for interfaces 
But gave error in 
ui.ts, emissions.selectors.ts,
So skipped that.

2020-11-01 19:24 UTC, PierreBresson requested changes
Very simples changes, otherwise looks good.
I've put back the `hacktoberfest`, I thought it was over... Timezone issue, sorry about that!

2020-11-01 19:24 UTC, PierreBresson commented on app/components/SelectableListItem/SelectableListItem.tsx
> +import Text from "components/Text";
import {Text} from "components";

2020-11-01 19:24 UTC, PierreBresson commented on app/navigation/Navigator/BottomTabNavigator.tsx
> +import TabBarIcon from "components/TabBarIcon";
import {TabBarIcon} from "components";

2020-11-01 19:24 UTC, PierreBresson commented on app/screens/ActDetail/ActDetailScreen.styles.ts
> +import { Layout } from "style/layout";
from "style";

2020-11-01 19:24 UTC, PierreBresson commented on app/screens/AddEmission/AddEmissionScreen.tsx
> +import { EmissionPayload } from "interfaces/emission/emission.interface";
`import { EmissionType, EmissionPayload } from "interfaces";`
To be able to do that you simply need to import 2 times in index.ts files inside `interface`

2020-11-01 19:24 UTC, PierreBresson commented on app/screens/AddEmission/components/AddEmissionButton/AddEmissionButton.tsx
> +import { EmissionPayload } from "interfaces/emission/emission.interface";
Same as previous comment

2020-11-01 19:24 UTC, PierreBresson commented on app/screens/Budget/ducks/__tests__/BudgetScreen.selectors.test.ts
> +import emissions from "ducks/emissions";
import {emissions} from "ducks";

2020-11-01 19:24 UTC, PierreBresson commented on app/screens/Emissions/components/EmissionsList/__tests__/EmissionsList.test.tsx
> +import emissions from "ducks/emissions";
import {emissions} from "ducks";

2020-11-01 19:24 UTC, PierreBresson commented on app/screens/Emissions/ducks/__tests__/EmissionsScreen.selectors.test.ts
> +import emissions from "ducks/emissions";
import {emissions} from "ducks";

2020-11-01 19:24 UTC, PierreBresson commented on app/redux/rootReducer.ts
> +import emissions from "ducks/emissions";
import {emissions,budget,userPreferences} from "ducks";

2020-11-01 19:24 UTC, PierreBresson commented on app/screens/Budget/components/NumberOfDaysVegetarian/ducks/__tests__/NumberOfDaysVegetarian.selectors.test.ts
> +import emissions from "ducks/emissions";
import {emissions} from "ducks";

2020-11-02 00:57 UTC, hb2708 commented
@PierreBresson thanks for review will fix the changes tonight. And also thanks for adding the tag back. But I think it will not count anymore as i was late to create pr. They are just counting 3 pr.

2020-11-03 15:32 UTC, hb2708 commented
@PierreBresson All should be fixed now  Give a look thanks.

2020-11-03 18:22 UTC, PierreBresson approved these changes
🏄‍♂️

2020-11-03 18:22 UTC, PierreBresson commented
@hb2708 thanks a lot !

2020-11-03 18:22 UTC, merged