Add import/export functionality
NMF-earth/nmf-app pull request #242
Opened 2020-11-01 16:25 UTC by iSasFTW

✅ I have read the [contributing file](https://github.com/NMF-earth/nmf-app/blob/master/contributing.md)

## Summary

This change closes #206. It adds import/export functionality, that allows the user to export the entire Redux store to a backup file that the user can then save to the desired location using a share sheet. (e.g saving to cloud services or local storage)

I haven't written any tests for this change, so that would be a todo, along with internationalization.

## Changelog

Added import/export functionality for backing up user data.

## Demo

![Screenshot_1](https://user-images.githubusercontent.com/13480136/97808404-5badda80-1c6f-11eb-99f1-e3828bd0d2ad.jpeg)
![Screenshot _2](https://user-images.githubusercontent.com/13480136/97808406-5f416180-1c6f-11eb-927b-4f5fdbd87385.jpeg)

2020-11-03 19:56 UTC, PierreBresson requested changes
Let's stick to emissions only export only like mentioned on the second point. Sorry I should have been more clear.
The PR is working well but is not following any convention used in the app. If you are willing to do the changes, let me know, I will take over.

2020-11-03 19:56 UTC, PierreBresson commented on package.json
> +    "expo-document-picker": "~8.4.0",
Please read contributing file : https://github.com/NMF-earth/nmf-app/blob/master/contributing.md => no ~ in package.json

2020-11-03 19:56 UTC, PierreBresson commented on app/screens/Settings/SettingsScreen.tsx
> +      title: "Export",
t("SETTINGS_SCREEN_EXPORT")

2020-11-03 19:56 UTC, PierreBresson commented on app/screens/Settings/SettingsScreen.tsx
> +      title: "Import",
t("SETTINGS_SCREEN_IMPORT")

2020-11-03 19:56 UTC, PierreBresson commented on app/screens/Settings/SettingsScreen.tsx
> +              store.dispatch(
let's only save emissions for now

2020-11-03 19:56 UTC, PierreBresson commented on app/screens/Settings/SettingsScreen.tsx
> +                emissions.actions.loadEmissionsFromImport(data.emissions)
```
...
const SettingsScreen = (props) => {
  const navigator = navigate(props.navigation); 
  const dispatch = useDispatch(); // add this
...
```
and then here simply : `dispatch(emissions.actions.loadEmissionsFromImport(data));`

2020-11-03 19:56 UTC, PierreBresson commented on app/screens/Settings/SettingsScreen.tsx
> +import store from "../../redux/store";
to be deleted

2020-11-03 19:56 UTC, PierreBresson commented on app/screens/Settings/SettingsScreen.tsx
> +        const exportData = JSON.stringify(store.getState());
Let's save only emissions : let's use `useSelector` instead
```
const emissions = useSelector(emissions.selectors.getAllEmissions)
JSON.stringify(emissions)
```

2020-11-04 19:03 UTC, iSasFTW commented
Ah, sorry about that, I must have somehow overlooked the part about only importing emissions.
I'll make the changes as soon as I can.

2020-11-06 08:30 UTC, closed without merging

2020-11-13 09:05 UTC, PierreBresson commented
@iSasFTW Due to #243 , `master` branch is now deleted and `main` is the new `master`, that's why the PR was closed and I can't reopen it, sorry :/

2020-11-13 10:44 UTC, iSasFTW commented
@PierreBresson Should I make a new PR onto the new branch?

2020-11-13 10:50 UTC, PierreBresson commented
@iSasFTW yes, against `main` branch

2021-04-15 09:55 UTC, PierreBresson commented
@saskakol done in https://github.com/NMF-earth/nmf-app/pull/263, thanks for the guidance 🙂