Add tests
NMF-earth/nmf-app pull request #382
Opened 2023-06-11 19:49 UTC by JohanRochet

✅ I have read the [contributing file](https://github.com/NMF-earth/nmf-app/blob/main/contributing.md)

## Summary
Hello, I'm a student in Computer Science and one of my lecturers charge me of choosing an open source application and just writing test on it. NMF-earth is the app I chose.

That's why I went a bit through the code and notice there might be some missing tests, specifically in the utils files. Here's why I wrote new unit tests with the assistance of Stryker, the mutation testing framework. Finally, I wanted to made tests on the user interaction, and so I designed one test for it in the screens. 

This pull request is then essentially some test added to the app. Don't hesitate to contact me for any question and excuse me if I made some _good_ _practice_ mistakes, it's the first time I program with react-native 😉.

2023-06-12 19:18 UTC, PierreBresson commented
Hello @JohanRochet 👋
Thanks for having a look :) Could you use jest instead of Stryker so we don't add any extra dependency?

2023-06-22 13:53 UTC, JohanRochet commented
I just deleted the dependency with stryker, unfortunately the interaction tests I wrote in MyLocationScreen.test.tsx require the use of React Native Testing Library which as far as I know can not be replaced by Jest. Do you want me to delete those tests or is it ok for you ?

2023-06-30 09:04 UTC, PierreBresson requested changes

2023-06-30 09:04 UTC, PierreBresson commented on app/screens/MyLocation/__tests__/MyLocationScreen.tests.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-var-requires
`import * as redux from 'react-redux'`

Then `const useSelectorMock = jest.spyOn(redux, "useSelector");` so you don't need the `// eslint-disable-next-line @typescript-eslint/no-var-requires`

2023-06-30 09:04 UTC, PierreBresson commented on app/screens/MyLocation/__tests__/MyLocationScreen.tests.tsx
> +  fireEvent.press(screen.root.findByProps({ title: ElectricityType.ireland.toUpperCase() }));
you don't need the extra library, you can use something like : 
`const item = root.findByProps({ title: ElectricityType.ireland.toUpperCase() });`
and then : 
`item.props.onPress();`
See `SocialMedia.test.tx` as reference

2023-11-02 18:59 UTC, PierreBresson commented
Closing for inactivity

2023-11-02 18:59 UTC, closed without merging